// src/types/index.ts

export interface UserProfile {
  id: string;              // Firebase Auth UID
  firstName: string;       // From Google displayName or manual
  lastName: string;        // From Google displayName or manual
  score: number;           // Starts at 1000, min 100
  imageUrl: string;        // Firebase Storage URL or Google photoURL
  voteCount: number;       // Total votes received (for volatility)
  createdAt: Date;
  isAuthUser: boolean;     // true = has auth account, false = vote-only profile
}

export interface Vote {
  id?: string;             // Auto-generated by Firestore
  winnerId: string;        // Profile ID of winner
  loserId: string;         // Profile ID of loser
  voterId: string;         // User UID who voted (for spam prevention)
  timestamp: Date;
  processed: boolean;      // false until Cloud Function processes it
}

export interface AuthUser {
  uid: string;
  displayName: string | null;
  email: string | null;
  photoURL: string | null;
}

export interface Ranking {
  rank: number;
  profile: UserProfile;
}

export interface VotingPair {
  profileA: UserProfile;
  profileB: UserProfile;
  outcomeA: ScoreChange;   // If A wins
  outcomeB: ScoreChange;   // If B wins
}

export interface ScoreChange {
  winnerChange: number;
  loserChange: number;
  winnerNewScore: number;
  loserNewScore: number;
}
