export const INITIAL_SCORE = 1000;
export const UNPROVEN_VOTE_CHANGE_MIN = 50;
export const UNPROVEN_VOTE_CHANGE_MAX = 150;
export const ESTABLISHED_VOTE_CHANGE_MIN = 5;
export const ESTABLISHED_VOTE_CHANGE_MAX = 30;
export const VOTE_BATCH_INTERVAL_MINUTES = 5;
export const VOTE_BATCH_INTERVAL_MAX_MINUTES = 30;